Issue #65 Integra ejemplos / html-css / 08-formularios
gbtec-ext-alexandreinsua/bootcamp_fe pull request #47
Opened 2024-10-30 10:39 UTC by Jorge338991

41 - Crear direcotorio ejemplos -> html-css -> 08 - Formularios

Luego se mueven ficheros de la raiz intro al directorio creado los siguientes ficheros:
formulario.html
formulario.css

Close #65

2024-10-30 11:04 UTC, Rubbeen99 approved these changes
Todo correcto.

2024-11-05 11:07 UTC, pacarescuba commented
Los nombres de los archivos están mal. Deben llevar el número del ejercicio. (08-formularios.css y 08-formularios.html)

2024-11-05 11:19 UTC, pacarescuba requested changes
Los nombres de los archivos están mal. Deben llevar el número del ejercicio. (08-formularios.css y 08-formularios.html)

2024-11-06 08:57 UTC, AlejandroMorono approved these changes
Correcto

2024-11-06 08:57 UTC, Xavifacendo approved these changes
creo que ya esta bien

2024-11-06 11:21 UTC, pacarescuba requested changes
Los archivos deben tener el nombre en plural

2024-11-06 11:21 UTC, Fansu7 commented
> Los archivos deben tener el nombre en plural

que pesao eres pacares

2024-11-06 11:37 UTC, gbtec-ext-alexandreinsua commented
Close #65

2024-11-07 08:03 UTC, pacarescuba commented
Esta PR va a añadir un bug. Se borrará el contenido de ejemplos/javascript/03-control-de-flujo

2024-11-07 08:12 UTC, pacarescuba approved these changes

2024-11-07 08:36 UTC, Jorge338991 commented
Confiamos en pacarescuba y palante

2024-11-07 08:36 UTC, merged