#42 Creación de carpeta 09-web-semantica
gbtec-ext-alexandreinsua/bootcamp_fe pull request #51
Opened 2024-10-30 10:48 UTC by jahzie

Creamos la carpeta 09-web-semantica y renombramos los archivos que colocamos dentro.

2024-10-30 11:02 UTC, anagarces submitted a review, later dismissed

2024-11-05 11:16 UTC, Noob-D-byte requested changes
Hay que editar el archivo 09-web-semantica.html puesto que está vacío.

2024-11-07 07:54 UTC, Noob-D-byte approved these changes

2024-11-07 08:36 UTC, Xavifacendo approved these changes
parece que se ve bien

2024-11-07 08:36 UTC, nievesfa approved these changes

2024-11-07 08:38 UTC, merged