70/mejorar vista index
gbtec-ext-alexandreinsua/bootcamp_fe pull request #96
Opened 2024-11-06 10:43 UTC by oscardasilvarodriguez

2024-11-06 11:08 UTC, RoiVigo91 requested changes
Hay otros cambios que pertenecen a otras Issues #79  #91

2024-11-07 08:52 UTC, gemenis1993 commented
esta pull request va a meter un bug

2024-11-07 09:07 UTC, gemenis1993 approved these changes

2024-11-07 09:10 UTC, AlejandroMorono approved these changes

2024-11-07 09:14 UTC, RoiVigo91 approved these changes

2024-11-07 09:14 UTC, merged